// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeting.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string               `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa78c4bfe266ddf, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Greeting) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Greeting) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Greeting) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa78c4bfe266ddf, []int{1}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	Greeting             *Greeting `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa78c4bfe266ddf, []int{2}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

func init() {
	proto.RegisterType((*Greeting)(nil), "v1.Greeting")
	proto.RegisterType((*PingRequest)(nil), "v1.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "v1.PingResponse")
}

func init() { proto.RegisterFile("greeting.proto", fileDescriptor_bfa78c4bfe266ddf) }

var fileDescriptor_bfa78c4bfe266ddf = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x95, 0x50, 0xd1, 0x72, 0x52, 0x28, 0xf2, 0x64, 0x65, 0xa1, 0xca, 0x14, 0x06, 0x5c,
	0x35, 0x30, 0x30, 0xb0, 0xb3, 0x22, 0xc3, 0x0b, 0xa4, 0xcd, 0xc1, 0xb2, 0x44, 0x6c, 0x63, 0xbb,
	0x79, 0x02, 0x1e, 0x1c, 0xc5, 0x17, 0xe8, 0xf8, 0x7f, 0xff, 0xb9, 0x7c, 0x40, 0x8c, 0x54, 0xe2,
	0xc1, 0xa1, 0x9d, 0xe4, 0x11, 0x99, 0xb1, 0xda, 0x6b, 0x52, 0x4e, 0xfb, 0xfa, 0x4e, 0x68, 0x2d,
	0xbe, 0x70, 0x17, 0xc8, 0xe1, 0xf4, 0xb9, 0xf3, 0x72, 0x44, 0xe7, 0xfb, 0xd1, 0xc4, 0xa1, 0xe6,
	0xa7, 0x80, 0xd5, 0xab, 0x45, 0xf4, 0x52, 0x09, 0x72, 0x03, 0xa5, 0x1c, 0x68, 0xb1, 0x2d, 0xda,
	0x2b, 0x5e, 0xca, 0x81, 0x50, 0x58, 0xa6, 0x93, 0xb4, 0x0c, 0x30, 0xc7, 0xb9, 0x19, 0xd1, 0xb9,
	0x5e, 0x20, 0xbd, 0x88, 0x4d, 0x8a, 0xe4, 0x09, 0x96, 0x47, 0x8b, 0xbd, 0xc7, 0x81, 0x2e, 0xb6,
	0x45, 0x5b, 0x75, 0x35, 0x8b, 0x0e, 0x2c, 0x3b, 0xb0, 0x8f, 0xec, 0xc0, 0xf3, 0x68, 0x73, 0x0d,
	0xd5, 0x9b, 0x54, 0x82, 0xe3, 0xf7, 0x09, 0x9d, 0x6f, 0x9e, 0x61, 0x1d, 0xa3, 0x33, 0x5a, 0x39,
	0x24, 0x2d, 0xac, 0x44, 0x92, 0x0c, 0x26, 0x55, 0xb7, 0x66, 0xd3, 0x9e, 0x65, 0x71, 0xfe, 0xd7,
	0x76, 0x2f, 0xb0, 0xc9, 0xf4, 0x3d, 0xb9, 0xde, 0xc3, 0x62, 0x3e, 0x46, 0x36, 0xf3, 0xca, 0xd9,
	0x97, 0xfa, 0xf6, 0x1f, 0xc4, 0x3f, 0x87, 0xcb, 0xe0, 0xf8, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x45, 0x41, 0xc1, 0xb6, 0x4f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetingServiceClient is the client API for GreetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetingServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type greetingServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetingServiceClient(cc *grpc.ClientConn) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

func (c *greetingServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/v1.GreetingService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingServiceServer is the server API for GreetingService service.
type GreetingServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedGreetingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetingServiceServer struct {
}

func (*UnimplementedGreetingServiceServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterGreetingServiceServer(s *grpc.Server, srv GreetingServiceServer) {
	s.RegisterService(&_GreetingService_serviceDesc, srv)
}

func _GreetingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GreetingService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GreetingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeting.proto",
}
