apiVersion: v1
kind: Service
metadata:
  name: service-c
  labels:
    app: service-c
    component: service
    version: "1.3.0"
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: service-c
    component: service
    version: "1.3.0"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-c
  labels:
    app: service-c
    component: service
    version: "1.3.0"
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-c
      component: service
      version: "1.3.0"
  template:
    metadata:
      labels:
        app: service-c
        component: service
        version: "1.3.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-c
        image: registry.hub.docker.com/garystafford/go-srv-c:1.3.0
        resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        env:
        - name: MONGO_CONN
          valueFrom:
            secretKeyRef:
              name: go-srv-config
              key: mongodb.conn
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent #Always
