apiVersion: v1
kind: Service
metadata:
  name: service-d
  labels:
    app: service-d
    component: service
    version: "1.5.0"
spec:
  ports:
  - name: http2
    protocol: TCP
    port: 50051
  selector:
    app: service-d
    component: service
    version: "1.5.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  labels:
    app: service-d
    component: service
    version: "1.5.0"
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-d
      component: service
      version: "1.5.0"
  template:
    metadata:
      labels:
        app: service-d
        component: service
        version: "1.5.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-d
        image: gcr.io/go-srv-demo/go-srv-d:1.5.0
        # resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        env:
        - name: LOG_LEVEL
          value: info
        - name: RABBITMQ_CONN
          valueFrom:
            secretKeyRef:
              name: go-srv-config
              key: rabbitmq.conn
        ports:
        - containerPort: 50051
        imagePullPolicy: Always
