apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
    component: service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: service-b
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
    component: service
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: service-b
      component: service
      version: v1
  template:
    metadata:
      labels:
        app: service-b
        component: service
        version: v1
    spec:
      containers:
        - name: service-b
          image: registry.hub.docker.com/garystafford/go-srv-b:1.6.7
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: LOG_LEVEL
              value: info
            - name: SERVICE_D_URL
              value: http://service-d.dev.svc.cluster.local:8080
            - name: SERVICE_E_URL
              value: http://service-e.dev.svc.cluster.local:8080
          ports:
            - containerPort: 8080
          imagePullPolicy: Always