apiVersion: v1
kind: Service
metadata:
  name: service-rev-proxy
  labels:
    app: service-rev-proxy
    component: service
    version: "1.5.0"
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: service-rev-proxy
    component: service
    version: "1.5.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-rev-proxy
  labels:
    app: service-rev-proxy
    component: service
    version: "1.5.0"
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-rev-proxy
      component: service
      version: "1.5.0"
  template:
    metadata:
      labels:
        app: service-rev-proxy
        component: service
        version: "1.5.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-rev-proxy
        image: registry.hub.docker.com/garystafford/go-srv-rev-proxy:1.5.0
        # resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        env:
        - name: LOG_LEVEL
          value: info
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
