apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongdb-atlas-external-mesh
spec:
  hosts:
  - {{ your_url_goes_here }}
  ports:
  - name: mongo
    number: 27017
    protocol: MONGO
  location: MESH_EXTERNAL
  resolution: NONE
